name: js-sdk-push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install packages for generation
      run: npm install -g @openapitools/openapi-generator-cli
    - name: Clone JS SDK Repo
      env:
        DEPLOY_KEY: ${{ secrets.JS_SDK_REPO_DEPLOY_PRIVATE_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        git clone git@github.com:uclapi/uclapi-js-sdk.git
    - name: Create open api generated folder
      run: openapi-generator-cli generate
    - name: Install packages for the folder
      run: |
        cd ./@uclapi/sdk
        npm install
    - name: Build the packages for the folder
      run: |
        cd ./@uclapi/sdk
        npm run build
    - name: Run test on the packages
      run: |
        cd ./@uclapi/sdk
        npm run test
    - name: Push JS SDK to GitHub repo
      env:
        DEPLOY_KEY: ${{ secrets.JS_SDK_REPO_DEPLOY_PRIVATE_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        cp -r ./@uclapi/sdk/* uclapi-js-sdk
        cd uclapi-js-sdk
        git config --global user.name "Shubham Jain"
        git config --global user.email "shubham@sjain.dev"
        git add docs src test .babelrc .gitignore package* README.md
        git commit -m "Update SDK"
        git push origin main
