name: js-sdk-push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: webfactory/ssh-agent@v0.4.1
      with:
          ssh-private-key: ${{ secrets.JS_SDK_REPO_DEPLOY_PRIVATE_KEY }}
    - name: Install packages for generation
      run: npm install -g @openapitools/openapi-generator-cli
    - name: Clone JS SDK Repo
      run: git clone git@github.com:uclapi/uclapi-js-sdk.git
    - name: Generate SDK source via openapi-generator
      run: openapi-generator-cli generate
    - name: Install dependencies for generated SDK
      run: cd ./@uclapi/sdk && npm install
    - name: Build generated SDK
      run: cd ./@uclapi/sdk && npm run build
    - name: Test generated SDK
      run: cd ./@uclapi/sdk && npm run test
    - name: Push SDK to GitHub repo
      run: |
        cp -rT ./@uclapi/sdk uclapi-js-sdk
        cd uclapi-js-sdk
        git config --global user.name "Shubham Jain"
        git config --global user.email "shubham@sjain.dev"
        git add docs src test .babelrc .gitignore package* README.md
        git commit -m "Update SDK"
        git push origin main
